# Generated by Django 5.2.3 on 2025-07-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaBlog', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador')], default='Borrador', max_length=10),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
