# Generated by Django 5.2.3 on 2025-07-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaBlog', '0004_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AddField(
            model_name='avatar',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
