# Generated by Django 5.2.3 on 2025-07-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaginaBlog', '0005_remove_post_imagen_avatar_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
